package com.example.demo.models;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Piece {
    @Id
    private String id; //unique id generated by mongoDB
    private int number; // Number from 1 to 12 that I will initialise when the game is created
    private Coordinate position; //The position on the board that the piece is occupying
    private boolean active; //If a piece is taken by opposition then this will be set to false
    private Player player;//Will get the username of the player when th game is started

    public Piece(int number, Coordinate position, boolean active, Player player) {
        this.number = number; //Id access for me for each counter
        this.position = position; //Coordinate of that piece on the board
        this.active = active; // Is this piece in the game or not
        this.player = player;
    }

    public void setActiveStatus(Boolean active){
        this.active = active;
    }

    public boolean getActiveStatus(){
        return active;
    }

    public void setPosition(Coordinate postion){
        this.position = postion;
    }

    public Coordinate getPosition(){
        return position;
    }

    public Player getPlayer(){
        return player;
    }

    public void setPieceNumber(int number){
        this.number = number;
    }

    public int getPieceNumber(){
        return number;
    }
}
