package com.example.demo.models;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Piece {
    @Id
    private String id; //unique id generated by mongoDB
    private int number; // Number from 1 to 12 that I will initialise when the game is created
    private Coordinate position; //The position on the board that the piece is occupying
    private boolean active; //If a piece is taken by opposition then this will be set to false
    private String playerId; //Will get the username of the player when th game is started

    public Piece(int number, Coordinate position, boolean active, String playerId) {
        this.number = number;
        this.position = position;
        this.active = active;
        this.playerId = playerId;
    }

    public void setActiveStatus(Boolean active){
        this.active = active;
    }

    public boolean getActiveStatus(){
        return active;
    }

    public void setPosition(Coordinate postion){
        this.position = postion;
    }

    public Coordinate getPosition(){
        return position;
    }
    

    public String getPlayerId(String playerId){
        return playerId;
    }

    public void setPieceNumber(int number){
        this.number = number;
    }

    public int getPieceNumber(){
        return number;
    }
}
